apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring-service
        image: srivyshnavi291001/microservice-monitoring:latest
        ports:
        - containerPort: 8080